name: CI Build prod image

on:
  workflow_call:
    inputs:
      tag:
        description: "tag to deploy from"
        default: ""
        required: false
        type: string

jobs:

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Tag name
        id: tag_name
        run: |
          if [ '${{ inputs.tag }}' = '' ]; then
            echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
          else
            echo ::set-output name=TAG::${{ inputs.tag }}
          fi
