
on:
  push:

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::add-mask::anothersecret"
      - run: echo "${{ secrets.SECRETCONTENT }}"
      - run: echo "SECRETCONTENT=anothersecret" >> $GITHUB_ENV
      - run: echo $SECRETCONTENT
        env:
          SECRETCONTENT: ${{ secrets.SECRETCONTENT }}
